Add short_grass
spoutn1k/mcmap pull request #101
Opened 2023-12-30 09:48 UTC by Netherwhal

2024-01-05 15:56 UTC, spoutn1k requested changes

2024-01-05 15:56 UTC, spoutn1k commented on scripts/average.sh
Although this is a good idea, the implementation of this script will make it harder to run on non-mac platforms. I will rework it to keep all of the code but make it more modular.

2024-01-05 16:57 UTC, spoutn1k commented
This works exactly like your script on my mac but will not fail on Linux. Please check on your side and I'll merge if no errors are reported !

2024-01-06 00:50 UTC, Netherwhal commented
Perfect, thanks @spoutn1k

2024-01-06 04:15 UTC, merged